### CADASTRAR USUÁRIO
POST http://localhost:5177/api/usuarios/cadastrar
Content-Type: application/json

{
  "nome": "Pedro Alves",
  "email": "pedro@example.com",
  "senha": "123456"
}

###

### FAZER LOGIN
POST http://localhost:5177/api/usuarios/login
Content-Type: application/json

{
  "email": "pedro@example.com",
  "senha": "123456"
}

###


